# generated by datamodel-codegen:
#   filename:  api.yaml
#   timestamp: 2026-03-02T22:04:36+00:00

from __future__ import annotations

from enum import StrEnum

from pydantic import AwareDatetime, BaseModel, Field


class DividendCashAction(StrEnum):
    REINVEST = "REINVEST"
    TO_ACCOUNT_CASH = "TO_ACCOUNT_CASH"


class AccountBucketDetailedResponse(BaseModel):
    creationDate: AwareDatetime | None = None
    dividendCashAction: DividendCashAction | None = None
    endDate: AwareDatetime | None = None
    goal: float | None = None
    icon: str | None = None
    id: int | None = None
    initialInvestment: float | None = None
    instrumentShares: dict[str, float] | None = None
    name: str | None = None
    publicUrl: str | None = None


class Status(StrEnum):
    AHEAD = "AHEAD"
    ON_TRACK = "ON_TRACK"
    BEHIND = "BEHIND"


class Cash(BaseModel):
    availableToTrade: float | None = Field(
        None, description="Funds available for investing."
    )
    inPies: float | None = Field(
        None,
        description="It’s the sum of the cash inside of all pies that is not yet invested.",
    )
    reservedForOrders: float | None = Field(
        None,
        description="The amount of cash reserved for pending orders. This cash is not available for placing new trades.",
    )


class DividendDetails(BaseModel):
    gained: float | None = None
    inCash: float | None = None
    reinvested: float | None = None


class DuplicateBucketRequest(BaseModel):
    icon: str | None = None
    name: str | None = None


class EnqueuedReportResponse(BaseModel):
    reportId: int | None = None


class TradingMethod(StrEnum):
    TOTV = "TOTV"
    OTC = "OTC"


class Type(StrEnum):
    TRADE = "TRADE"
    STOCK_SPLIT = "STOCK_SPLIT"
    STOCK_DISTRIBUTION = "STOCK_DISTRIBUTION"
    FOP = "FOP"
    FOP_CORRECTION = "FOP_CORRECTION"
    CUSTOM_STOCK_DISTRIBUTION = "CUSTOM_STOCK_DISTRIBUTION"
    EQUITY_RIGHTS = "EQUITY_RIGHTS"
    SCRIP_STOCK_DIVIDENDS = "SCRIP_STOCK_DIVIDENDS"
    STOCK_DIVIDENDS = "STOCK_DIVIDENDS"
    STOCK_ACQUISITION = "STOCK_ACQUISITION"
    CASH_AND_STOCK_ACQUISITION = "CASH_AND_STOCK_ACQUISITION"
    SPIN_OFF = "SPIN_OFF"


class Type1(StrEnum):
    ORDINARY = "ORDINARY"
    BONUS = "BONUS"
    PROPERTY_INCOME = "PROPERTY_INCOME"
    RETURN_OF_CAPITAL_NON_US = "RETURN_OF_CAPITAL_NON_US"
    DEMERGER = "DEMERGER"
    INTEREST = "INTEREST"
    CAPITAL_GAINS_DISTRIBUTION_NON_US = "CAPITAL_GAINS_DISTRIBUTION_NON_US"
    INTERIM_LIQUIDATION = "INTERIM_LIQUIDATION"
    ORDINARY_MANUFACTURED_PAYMENT = "ORDINARY_MANUFACTURED_PAYMENT"
    BONUS_MANUFACTURED_PAYMENT = "BONUS_MANUFACTURED_PAYMENT"
    PROPERTY_INCOME_MANUFACTURED_PAYMENT = "PROPERTY_INCOME_MANUFACTURED_PAYMENT"
    RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT = (
        "RETURN_OF_CAPITAL_NON_US_MANUFACTURED_PAYMENT"
    )
    DEMERGER_MANUFACTURED_PAYMENT = "DEMERGER_MANUFACTURED_PAYMENT"
    INTEREST_MANUFACTURED_PAYMENT = "INTEREST_MANUFACTURED_PAYMENT"
    CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT = (
        "CAPITAL_GAINS_DISTRIBUTION_NON_US_MANUFACTURED_PAYMENT"
    )
    INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT = (
        "INTERIM_LIQUIDATION_MANUFACTURED_PAYMENT"
    )
    INTEREST_PAID_BY_US_OBLIGORS = "INTEREST_PAID_BY_US_OBLIGORS"
    INTEREST_PAID_BY_FOREIGN_CORPORATIONS = "INTEREST_PAID_BY_FOREIGN_CORPORATIONS"
    DIVIDENDS_PAID_BY_US_CORPORATIONS = "DIVIDENDS_PAID_BY_US_CORPORATIONS"
    DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS = "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS"
    CAPITAL_GAINS = "CAPITAL_GAINS"
    REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES = (
        "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES"
    )
    OTHER_INCOME = "OTHER_INCOME"
    QUALIFIED_INVESTMENT_ENTITY = "QUALIFIED_INVESTMENT_ENTITY"
    TRUST_DISTRIBUTION = "TRUST_DISTRIBUTION"
    PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION = (
        "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION"
    )
    CAPITAL_GAINS_DISTRIBUTION = "CAPITAL_GAINS_DISTRIBUTION"
    RETURN_OF_CAPITAL = "RETURN_OF_CAPITAL"
    OTHER_DIVIDEND_EQUIVALENT = "OTHER_DIVIDEND_EQUIVALENT"
    TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES = (
        "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES"
    )
    PTP_UNCHARACTERISED_INCOME = "PTP_UNCHARACTERISED_INCOME"
    MULTIPLE_1042S_TAX_COMPONENTS = "MULTIPLE_1042S_TAX_COMPONENTS"
    DIVIDEND = "DIVIDEND"
    SHORT_TERM_CAPITAL_GAINS = "SHORT_TERM_CAPITAL_GAINS"
    LONG_TERM_CAPITAL_GAINS = "LONG_TERM_CAPITAL_GAINS"
    PROPERTY_INCOME_DISTRIBUTION = "PROPERTY_INCOME_DISTRIBUTION"
    TAX_EXEMPTED = "TAX_EXEMPTED"
    INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT = (
        "INTEREST_PAID_BY_US_OBLIGORS_MANUFACTURED_PAYMENT"
    )
    INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "INTEREST_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "DIVIDENDS_PAID_BY_US_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT = (
        "DIVIDENDS_PAID_BY_FOREIGN_CORPORATIONS_MANUFACTURED_PAYMENT"
    )
    CAPITAL_GAINS_MANUFACTURED_PAYMENT = "CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT = (
        "REAL_PROPERTY_INCOME_AND_NATURAL_RESOURCES_ROYALTIES_MANUFACTURED_PAYMENT"
    )
    OTHER_INCOME_MANUFACTURED_PAYMENT = "OTHER_INCOME_MANUFACTURED_PAYMENT"
    QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT = (
        "QUALIFIED_INVESTMENT_ENTITY_MANUFACTURED_PAYMENT"
    )
    TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT = "TRUST_DISTRIBUTION_MANUFACTURED_PAYMENT"
    PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "PUBLICLY_TRADED_PARTNERSHIP_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "CAPITAL_GAINS_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT = "RETURN_OF_CAPITAL_MANUFACTURED_PAYMENT"
    OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT = (
        "OTHER_DIVIDEND_EQUIVALENT_MANUFACTURED_PAYMENT"
    )
    TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT = (
        "TAX_EVENT_1446F_FOR_PUBLICLY_TRADED_SECURITIES_MANUFACTURED_PAYMENT"
    )
    PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT = (
        "PTP_UNCHARACTERISED_INCOME_MANUFACTURED_PAYMENT"
    )
    MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT = (
        "MULTIPLE_1042S_TAX_COMPONENTS_MANUFACTURED_PAYMENT"
    )
    DIVIDEND_MANUFACTURED_PAYMENT = "DIVIDEND_MANUFACTURED_PAYMENT"
    SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT = (
        "SHORT_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    )
    LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT = (
        "LONG_TERM_CAPITAL_GAINS_MANUFACTURED_PAYMENT"
    )
    PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT = (
        "PROPERTY_INCOME_DISTRIBUTION_MANUFACTURED_PAYMENT"
    )
    TAX_EXEMPTED_MANUFACTURED_PAYMENT = "TAX_EXEMPTED_MANUFACTURED_PAYMENT"


class Type2(StrEnum):
    WITHDRAW = "WITHDRAW"
    DEPOSIT = "DEPOSIT"
    FEE = "FEE"
    TRANSFER = "TRANSFER"


class HistoryTransactionItem(BaseModel):
    amount: float | None = Field(
        None, description="Amount in the currency of the transaction"
    )
    currency: str | None = Field(None, description="Currency of the transaction")
    dateTime: AwareDatetime | None = None
    reference: str | None = Field(None, description="ID")
    type: Type2 | None = None


class Instrument(BaseModel):
    currency: str | None = Field(
        None, description="Instrument currency in ISO 4217 format."
    )
    isin: str | None = Field(None, description="ISIN of the instrument.")
    name: str | None = Field(None, description="Name of the instrument.")
    ticker: str | None = Field(
        None, description="Unique instrument identifier.", examples=["AAPL_US_EQ"]
    )


class Name(StrEnum):
    DELISTED = "DELISTED"
    SUSPENDED = "SUSPENDED"
    NO_LONGER_TRADABLE = "NO_LONGER_TRADABLE"
    MAX_POSITION_SIZE_REACHED = "MAX_POSITION_SIZE_REACHED"
    APPROACHING_MAX_POSITION_SIZE = "APPROACHING_MAX_POSITION_SIZE"
    COMPLEX_INSTRUMENT_APP_TEST_REQUIRED = "COMPLEX_INSTRUMENT_APP_TEST_REQUIRED"
    PRICE_TOO_LOW = "PRICE_TOO_LOW"


class Severity(StrEnum):
    IRREVERSIBLE = "IRREVERSIBLE"
    REVERSIBLE = "REVERSIBLE"
    INFORMATIVE = "INFORMATIVE"


class InstrumentIssue(BaseModel):
    name: Name | None = None
    severity: Severity | None = None


class InvestmentResult(BaseModel):
    priceAvgInvestedValue: float | None = None
    priceAvgResult: float | None = None
    priceAvgResultCoef: float | None = None
    priceAvgValue: float | None = None


class Investments(BaseModel):
    currentValue: float | None = Field(
        None, description="Current value of all the investments."
    )
    realizedProfitLoss: float | None = Field(
        None,
        description="The all-time realised profit loss from all of the trades executed.",
    )
    totalCost: float | None = Field(
        None,
        description="The cost basis of your current investments. The total amount of funds you've invested in the shares you currently own.",
    )
    unrealizedProfitLoss: float | None = Field(
        None,
        description="The potential profit/loss of your current investments, showing how much you could gain or lose if you were to sell them now.",
    )


class MarketRequest(BaseModel):
    extendedHours: bool | None = Field(False, examples=[True])
    quantity: float | None = Field(None, examples=[0.1])
    ticker: str | None = Field(None, examples=["AAPL_US_EQ"])


class InitiatedFrom(StrEnum):
    API = "API"
    IOS = "IOS"
    ANDROID = "ANDROID"
    WEB = "WEB"
    SYSTEM = "SYSTEM"
    AUTOINVEST = "AUTOINVEST"


class Side(StrEnum):
    BUY = "BUY"
    SELL = "SELL"


class Status1(StrEnum):
    LOCAL = "LOCAL"
    UNCONFIRMED = "UNCONFIRMED"
    CONFIRMED = "CONFIRMED"
    NEW = "NEW"
    CANCELLING = "CANCELLING"
    CANCELLED = "CANCELLED"
    PARTIALLY_FILLED = "PARTIALLY_FILLED"
    FILLED = "FILLED"
    REJECTED = "REJECTED"
    REPLACING = "REPLACING"
    REPLACED = "REPLACED"


class Strategy(StrEnum):
    QUANTITY = "QUANTITY"
    VALUE = "VALUE"


class Type3(StrEnum):
    LIMIT = "LIMIT"
    STOP = "STOP"
    MARKET = "MARKET"
    STOP_LIMIT = "STOP_LIMIT"


class PaginatedResponseHistoryTransactionItem(BaseModel):
    items: list[HistoryTransactionItem] | None = None
    nextPagePath: str | None = None


class PieRequest(BaseModel):
    dividendCashAction: DividendCashAction | None = None
    endDate: AwareDatetime | None = None
    goal: float | None = Field(
        None, description="Total desired value of the pie in account currency"
    )
    icon: str | None = None
    instrumentShares: dict[str, float] | None = Field(
        None, examples=[{"AAPL_US_EQ": 0.5, "MSFT_US_EQ": 0.5}]
    )
    name: str | None = None


class PositionWalletImpact(BaseModel):
    currency: str | None = Field(
        None,
        description="The currency code used to represent all the wallet impact information.",
    )
    currentValue: float | None = Field(
        None, description="The current market value of the position."
    )
    fxImpact: float | None = Field(
        None,
        description="The positive or negative impact on the position's value due to currency rate changes.",
    )
    totalCost: float | None = Field(
        None, description="The total cost paid for the position."
    )
    unrealizedProfitLoss: float | None = Field(
        None,
        description="The unrealized profit & loss for the position. Calculated as currentValue - totalCost.",
    )


class ReportDataIncluded(BaseModel):
    includeDividends: bool | None = None
    includeInterest: bool | None = None
    includeOrders: bool | None = None
    includeTransactions: bool | None = None


class Status2(StrEnum):
    Queued = "Queued"
    Processing = "Processing"
    Running = "Running"
    Canceled = "Canceled"
    Failed = "Failed"
    Finished = "Finished"


class ReportResponse(BaseModel):
    dataIncluded: ReportDataIncluded | None = None
    downloadLink: str | None = None
    reportId: int | None = None
    status: Status2 | None = None
    timeFrom: AwareDatetime | None = None
    timeTo: AwareDatetime | None = None


class Name1(StrEnum):
    COMMISSION_TURNOVER = "COMMISSION_TURNOVER"
    CURRENCY_CONVERSION_FEE = "CURRENCY_CONVERSION_FEE"
    FINRA_FEE = "FINRA_FEE"
    FRENCH_TRANSACTION_TAX = "FRENCH_TRANSACTION_TAX"
    PTM_LEVY = "PTM_LEVY"
    STAMP_DUTY = "STAMP_DUTY"
    STAMP_DUTY_RESERVE_TAX = "STAMP_DUTY_RESERVE_TAX"
    TRANSACTION_FEE = "TRANSACTION_FEE"


class Tax(BaseModel):
    chargedAt: AwareDatetime | None = None
    currency: str | None = None
    name: Name1 | None = None
    quantity: float | None = None


class Type4(StrEnum):
    OPEN = "OPEN"
    CLOSE = "CLOSE"
    BREAK_START = "BREAK_START"
    BREAK_END = "BREAK_END"
    PRE_MARKET_OPEN = "PRE_MARKET_OPEN"
    AFTER_HOURS_OPEN = "AFTER_HOURS_OPEN"
    AFTER_HOURS_CLOSE = "AFTER_HOURS_CLOSE"
    OVERNIGHT_OPEN = "OVERNIGHT_OPEN"


class TimeEvent(BaseModel):
    date: AwareDatetime | None = None
    type: Type4 | None = None


class TimeValidity(StrEnum):
    DAY = "DAY"
    GOOD_TILL_CANCEL = "GOOD_TILL_CANCEL"


class Type5(StrEnum):
    CRYPTOCURRENCY = "CRYPTOCURRENCY"
    ETF = "ETF"
    FOREX = "FOREX"
    FUTURES = "FUTURES"
    INDEX = "INDEX"
    STOCK = "STOCK"
    WARRANT = "WARRANT"
    CRYPTO = "CRYPTO"
    CVR = "CVR"
    CORPACT = "CORPACT"


class TradableInstrument(BaseModel):
    addedOn: AwareDatetime | None = Field(None, description="On the platform since")
    currencyCode: str | None = Field(None, description="ISO 4217", examples=["USD"])
    extendedHours: bool | None = None
    isin: str | None = None
    maxOpenQuantity: float | None = None
    name: str | None = None
    shortName: str | None = None
    ticker: str | None = Field(
        None, description="Unique identifier", examples=["AAPL_US_EQ"]
    )
    type: Type5 | None = Field(None, examples=["ETF"])
    workingScheduleId: int | None = Field(
        None, description="Get items in the /exchanges endpoint"
    )


class WorkingSchedule(BaseModel):
    id: int | None = None
    timeEvents: list[TimeEvent] | None = None


class AccountBucketInstrumentResult(BaseModel):
    currentShare: float | None = None
    expectedShare: float | None = None
    issues: list[InstrumentIssue] | None = None
    ownedQuantity: float | None = None
    result: InvestmentResult | None = None
    ticker: str | None = None


class AccountBucketInstrumentsDetailedResponse(BaseModel):
    instruments: list[AccountBucketInstrumentResult] | None = None
    settings: AccountBucketDetailedResponse | None = None


class AccountBucketResultResponse(BaseModel):
    cash: float | None = Field(
        None, description="Amount of money put into the pie in account currency"
    )
    dividendDetails: DividendDetails | None = None
    id: int | None = None
    progress: float | None = Field(
        None, description="Progress of the pie based on the set goal", examples=[0.5]
    )
    result: InvestmentResult | None = None
    status: Status | None = Field(
        None, description="Status of the pie based on the set goal"
    )


class AccountSummary(BaseModel):
    cash: Cash | None = None
    currency: str | None = Field(
        None, description="Primary account currency in ISO 4217 format."
    )
    id: int | None = Field(
        None,
        description="Primary trading account number. This is the same account ID you would see in the Trading 212 web or mobile application.",
    )
    investments: Investments | None = None
    totalValue: float | None = Field(
        None, description="Investments value in your account's primary currency."
    )


class Exchange(BaseModel):
    id: int | None = None
    name: str | None = None
    workingSchedules: list[WorkingSchedule] | None = None


class FillWalletImpact(BaseModel):
    currency: str | None = None
    fxRate: float | None = None
    netValue: float | None = None
    realisedProfitLoss: float | None = None
    taxes: list[Tax] | None = None


class HistoryDividendItem(BaseModel):
    amount: float | None = Field(None, description="In account's primary currency.")
    amountInEuro: float | None = None
    currency: str | None = Field(None, description="The account's primary currency.")
    grossAmountPerShare: float | None = Field(
        None, description="In instrument currency"
    )
    instrument: Instrument | None = None
    paidOn: AwareDatetime | None = None
    quantity: float | None = None
    reference: str | None = None
    ticker: str | None = None
    tickerCurrency: str | None = None
    type: Type1 | None = None


class LimitRequest(BaseModel):
    limitPrice: float | None = Field(None, examples=[100.23])
    quantity: float | None = Field(None, examples=[0.1])
    ticker: str | None = Field(None, examples=["AAPL_US_EQ"])
    timeValidity: TimeValidity | None = Field(
        None, description="Expiration", examples=["DAY"]
    )


class Order(BaseModel):
    createdAt: AwareDatetime | None = Field(
        None, description="The ISO 8601 formatted date of when the order was created."
    )
    currency: str | None = Field(
        None, description="The currency used for the order in ISO 4217 format."
    )
    extendedHours: bool | None = Field(
        None,
        description="If true, the order is eligible for execution outside regular trading hours.",
    )
    filledQuantity: float | None = Field(
        None,
        description="The number of shares that have been successfully executed. Applicable to quantity orders.",
    )
    filledValue: float | None = Field(
        None,
        description="The total monetary value of the executed portion of the order. Applicable  to orders placed by value.Note: Placing orders by value is not currently supported via the API but can be done through other Trading 212 platforms.",
    )
    id: int | None = Field(
        None, description="A unique, system-generated identifier for the order."
    )
    initiatedFrom: InitiatedFrom | None = Field(
        None, description="How the order was initiated."
    )
    instrument: Instrument | None = None
    limitPrice: float | None = Field(
        None, description="Applicable to LIMIT and STOP_LIMIT orders."
    )
    quantity: float | None = Field(
        None,
        description="The total number of shares requested. Applicable to quantity orders.",
    )
    side: Side | None = Field(
        None, description="Indicates whether the order is BUY or SELL."
    )
    status: Status1 | None = Field(
        None, description="The current state of the order in its lifecycle."
    )
    stopPrice: float | None = Field(
        None, description="Applicable to STOP and STOP_LIMIT orders."
    )
    strategy: Strategy | None = Field(
        None,
        description="The strategy used to place the order, either by QUANTITY or VALUE. The API currently only supports placing orders by QUANTITY.",
    )
    ticker: str | None = Field(
        None,
        description="Unique instrument identifier. Get from the /instruments endpoint",
        examples=["AAPL_US_EQ"],
    )
    timeInForce: TimeValidity | None = None
    type: Type3 | None = None
    value: float | None = Field(
        None,
        description="The total monetary value of the order. Applicable to value orders.",
    )


class PaginatedResponseHistoryDividendItem(BaseModel):
    items: list[HistoryDividendItem] | None = None
    nextPagePath: str | None = None


class Position(BaseModel):
    averagePricePaid: float | None = Field(
        None, description="Average price paid, in instrument currency, per share."
    )
    createdAt: AwareDatetime | None = Field(
        None, description="The ISO 8601 formatted date of when the position was opened."
    )
    currentPrice: float | None = Field(
        None, description="Current price, in instrument currency, of a single share."
    )
    instrument: Instrument | None = None
    quantity: float | None = Field(None, description="Total quantity of shares owned.")
    quantityAvailableForTrading: float | None = Field(
        None, description="Quantity of shares available for trading."
    )
    quantityInPies: float | None = Field(
        None, description="Quantity of shares currently used in pie."
    )
    walletImpact: PositionWalletImpact | None = Field(
        None,
        description="Collects the financial impact of the position on the user's wallet.",
    )


class PublicReportRequest(BaseModel):
    dataIncluded: ReportDataIncluded | None = None
    timeFrom: AwareDatetime | None = None
    timeTo: AwareDatetime | None = None


class StopLimitRequest(BaseModel):
    limitPrice: float | None = Field(None, examples=[100.23])
    quantity: float | None = Field(None, examples=[0.1])
    stopPrice: float | None = Field(None, examples=[100.23])
    ticker: str | None = Field(None, examples=["AAPL_US_EQ"])
    timeValidity: TimeValidity | None = Field(
        None, description="Expiration", examples=["DAY"]
    )


class StopRequest(BaseModel):
    quantity: float | None = Field(None, examples=[0.1])
    stopPrice: float | None = Field(None, examples=[100.23])
    ticker: str | None = Field(None, examples=["AAPL_US_EQ"])
    timeValidity: TimeValidity | None = Field(
        None, description="Expiration", examples=["DAY"]
    )


class Fill(BaseModel):
    filledAt: AwareDatetime | None = None
    id: int | None = None
    price: float | None = None
    quantity: float | None = None
    tradingMethod: TradingMethod | None = None
    type: Type | None = None
    walletImpact: FillWalletImpact | None = None


class HistoricalOrder(BaseModel):
    fill: Fill | None = None
    order: Order | None = None


class PaginatedResponseHistoricalOrder(BaseModel):
    items: list[HistoricalOrder] | None = None
    nextPagePath: str | None = None
