name: Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: arc-runner-set-t212-cli
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Install uv
        uses: astral-sh/setup-uv@v8.3.2
      - name: Python Semantic Release
        uses: python-semantic-release/python-semantic-release@v9.21.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
